[package]
name = "operator-history-sdk"
version = "0.0.1"
edition = "2021"

[dependencies]
borsh = { workspace = true }
shank = { workspace = true }
solana-program = { workspace = true }
thiserror = { workspace = true }
